import { Container } from '../types/purchaseOrder';

export const mockContainers: Container[] = [
  {
    id: 1,
    containerName: "Container Alpha",
    referenceContainer: "Ref 1",
    containerNumber: "CSNU1234567",
    containerRegion: "North America",
    departureDate: "2026-01-15",
    arrivalDate: "2026-02-01",
    deliveryStatus: "Delivered",
  },
  {
    id: 2,
    containerName: "Container Beta",
    referenceContainer: "Ref 2",
    containerNumber: "MSCU9876543",
    containerRegion: "Europe",
    departureDate: "2026-01-20",
    arrivalDate: "2026-02-10",
    deliveryStatus: "InTransit",
  },
  {
    id: 3,
    containerName: "Container Gamma",
    referenceContainer: "Ref 3",
    containerNumber: "HLCU5551234",
    containerRegion: "Asia Pacific",
    departureDate: "2026-01-18",
    arrivalDate: "2026-02-05",
    deliveryStatus: "Delivered",
  },
  {
    id: 4,
    containerName: "Container Delta",
    referenceContainer: "Ref 4",
    containerNumber: "TCLU7778889",
    containerRegion: "Middle East",
    departureDate: "2026-01-25",
    arrivalDate: "2026-02-15",
    deliveryStatus: "InTransit",
  },
  {
    id: 5,
    containerName: "Container Epsilon",
    referenceContainer: "Ref 5",
    containerNumber: "OOLU3334445",
    containerRegion: "South America",
    departureDate: "2026-01-10",
    arrivalDate: "2026-01-28",
    deliveryStatus: "Delivered",
  },
  {
    id: 6,
    containerName: "Container Epsilon",
    referenceContainer: "Ref 6",
    containerNumber: "OOLU3334445",
    containerRegion: "South America",
    departureDate: "2026-01-10",
    arrivalDate: "2026-01-28",
    deliveryStatus: "Delivered",
  },
  {
    id: 7,
    containerName: "Container Epsilon",
    referenceContainer: "Ref 7",
    containerNumber: "OOLU3334445",
    containerRegion: "South America",
    departureDate: "2026-01-10",
    arrivalDate: "2026-01-28",
    deliveryStatus: "Delivered",
  },
  {
    id: 8,
    containerName: "Container Epsilon",
    referenceContainer: "Ref 8",
    containerNumber: "OOLU3334445",
    containerRegion: "South America",
    departureDate: "2026-01-10",
    arrivalDate: "2026-01-28",
    deliveryStatus: "Delivered",
  },
  {
    id: 9,
    containerName: "Container Epsilon",
    referenceContainer: "Ref 9",
    containerNumber: "OOLU3334445",
    containerRegion: "South America",
    departureDate: "2026-01-10",
    arrivalDate: "2026-01-28",
    deliveryStatus: "Delivered",
  },
  {
    id: 10,
    containerName: "Container Epsilon",
    referenceContainer: "Ref 10",
    containerNumber: "OOLU3334445",
    containerRegion: "South America",
    departureDate: "2026-01-10",
    arrivalDate: "2026-01-28",
    deliveryStatus: "Delivered",
  },
  {
    id: 11,
    containerName: "Container Epsilon",
    referenceContainer: "Ref 11",
    containerNumber: "OOLU3334445",
    containerRegion: "South America",
    departureDate: "2026-01-10",
    arrivalDate: "2026-01-28",
    deliveryStatus: "Delivered",
  },
];

export const PAGINATION_MODEL = { page: 0, pageSize: 100 };
