import { StockReportRow } from '../types/stockReport';

export const STOCK_REPORT_DATA: StockReportRow[] = [
  {
    id: 1,
    Data_From: "12/14/2025",
    UploadDate: "2/12/2026",
    WareHouseCode: "CA",
    CategoryName: "ABANDONED ITEMS",
    ItemNumber: "*APR-RP",
    ItemTitle: "ARM PAD KING REX",
    SoldQuantity: 0,
    Available: 0,
  },
  {
    id: 2,
    Data_From: "12/14/2025",
    UploadDate: "2/12/2026",
    WareHouseCode: "DE",
    CategoryName: "ABANDONED ITEMS",
    ItemNumber: "*APR-RP",
    ItemTitle: "ARM PAD KING REX",
    SoldQuantity: 0,
    Available: 0,
  },
  {
    id: 3,
    Data_From: "12/14/2025",
    UploadDate: "2/12/2026",
    WareHouseCode: "UK",
    CategoryName: "ABANDONED ITEMS",
    ItemNumber: "*APR-RP",
    ItemTitle: "ARM PAD KING REX",
    SoldQuantity: 0,
    Available: 0,
  },
  {
    id: 4,
    Data_From: "12/14/2025",
    UploadDate: "2/12/2026",
    WareHouseCode: "US",
    CategoryName: "ABANDONED ITEMS",
    ItemNumber: "*APR-RP",
    ItemTitle: "ARM PAD KING REX",
    SoldQuantity: 0,
    Available: 0,
  },
  {
    id: 5,
    Data_From: "12/14/2025",
    UploadDate: "2/12/2026",
    WareHouseCode: "CA",
    CategoryName: "ABANDONED ITEMS",
    ItemNumber: "*APR-RP",
    ItemTitle: "ARM PAD KING REX",
    SoldQuantity: 0,
    Available: 0,
  },
  {
    id: 6,
    Data_From: "12/14/2025",
    UploadDate: "2/12/2026",
    WareHouseCode: "DE",
    CategoryName: "ABANDONED ITEMS",
    ItemNumber: "*APR-RP",
    ItemTitle: "ARM PAD KING REX",
    SoldQuantity: 0,
    Available: 0,
  },
  {
    id: 7,
    Data_From: "12/14/2025",
    UploadDate: "2/12/2026",
    WareHouseCode: "UK",
    CategoryName: "ABANDONED ITEMS",
    ItemNumber: "*APR-RP",
    ItemTitle: "ARM PAD KING REX",
    SoldQuantity: 0,
    Available: 0,
  },
  {
    id: 8,
    Data_From: "12/14/2025",
    UploadDate: "2/12/2026",
    WareHouseCode: "US",
    CategoryName: "ABANDONED ITEMS",
    ItemNumber: "*APR-RP",
    ItemTitle: "ARM PAD KING REX",
    SoldQuantity: 0,
    Available: 0,
  },
];

export const PAGINATION_MODEL = { page: 0, pageSize: 100 };
