export const DEFAULT_PAGINATION_MODEL = { page: 0, pageSize: 100 };

export const PURCHASE_ORDER_PAGINATION_MODEL = DEFAULT_PAGINATION_MODEL;
export const STOCK_REPORT_PAGINATION_MODEL = DEFAULT_PAGINATION_MODEL;
export const WH_CONTAINER_REPORT_PAGINATION_MODEL = DEFAULT_PAGINATION_MODEL;
export const COMBINED_REPORT_PAGINATION_MODEL = DEFAULT_PAGINATION_MODEL;

