import { GridColDef } from "@mui/x-data-grid";

export const generateWarehouseColumns = (): GridColDef[] => [
  {
    field: "Data_From",
    headerName: "Data_From",
    width: 150,
    sortable: true,
    filterable: true,
  },
  {
    field: "CategoryName",
    headerName: "Category Name",
    width: 150,
    sortable: true,
    filterable: true,
  },
  {
    field: "itemNumber",
    headerName: "Item Number",
    width: 150,
    sortable: true,
    filterable: true,
  },
  {
    field: "ContainerName",
    headerName: "Container Name",
    width: 200,
    sortable: true,
    filterable: true,
  },
  {
    field: "values",
    headerName: "Values",
    width: 150,
    sortable: true,
    filterable: true,
  },
  {
    field: "ContainerRegion",
    headerName: "Container Region",
    width: 200,
    sortable: true,
    filterable: true,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "DepartureDate",
    headerName: "Departure Date",
    width: 130,
    sortable: true,
    filterable: true,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "ArrivalDate",
    headerName: "Arrival Date",
    width: 130,
    sortable: true,
    filterable: true,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "CurrentDate",
    headerName: "Current Date",
    width: 130,
    sortable: true,
    filterable: true,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "LeftDays",
    headerName: "Left Days",
    width: 130,
    sortable: true,
    filterable: true,
    headerAlign: "center",
    align: "center",
  },
]