import { GridColDef } from "@mui/x-data-grid";

export const generateWarehouseColumns = (): GridColDef[] => [
  {
    field: "CategoryName",
    headerName: "Category Name",
    width: 150,
    sortable: true,
    filterable: true,
  },
  {
    field: "ItemNumber",
    headerName: "Item Number",
    width: 150,
    sortable: true,
    filterable: true,
  },
  {
    field: "ContainerName",
    headerName: "Container Name",
    width: 150,
    sortable: true,
    filterable: true,
  },
  {
    field: "ContainerRegion",
    headerName: "Warehouse",
    width: 150,
    sortable: true,
    filterable: true,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "IntransitQuantity",
    headerName: "Intransit Qty",
    width: 120,
    sortable: true,
    filterable: true,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "ContainerNumber",
    headerName: "Container #",
    width: 110,
    sortable: true,
    filterable: true,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "DepartureDate",
    headerName: "Departure Date",
    width: 140,
    sortable: true,
    filterable: true,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "ArrivalDate",
    headerName: "Arrival Date",
    width: 140,
    sortable: true,
    filterable: true,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "LeftDays",
    headerName: "Left Days",
    width: 100,
    sortable: true,
    filterable: true,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "UploadDate",
    headerName: "Current Date",
    width: 140,
    sortable: true,
    filterable: true,
    headerAlign: "center",
    align: "center",
  },
]